### ISSUE TITLE
[1.12.2] bug /gate setfrom "There is not enough room for a gate to open here"

### ISSUE THREAD

**Issue by Akashiic** [ChanceSD/AncientGates#28] opened 2019-11-29 19:39 UTC
**Describe the bug**
Good afternoon, I was wondering how to fix this bug from the "/ gate setfrom" command that sends me a message saying "There is not enough room for a gate to open here" everywhere I try to set a portal position

**To Reproduce**
1. /gate setfrom <ID>
2. Enter
3. Bug "here is not enough room for a gate to open here"

**Expected behavior**
Nothing
Print: https://prnt.sc/q40ghk

**Plugin and Server version**
Plugin version: https://prnt.sc/q40ity
2.2.1 Recent

**Screenshots**
Portal: https://prnt.sc/q40gxi
Command: https://prnt.sc/q40h8s
Error: https://prnt.sc/q40hjf
Console: https://prnt.sc/q40ghk

**Additional context**

**Comment by ChanceSD** [comment] 2019-12-11 21:54
Sorry about the delay, have you tried using a vanilla block as the floor of the gate?
I see that you appear to be using a modpack, could be because of that since i created a gate with those exact dimensions on a test server and it opened without issues.

This error happens when the location you are standing in is not AIR even though it appears to be. I'm also adding a debug message on the next update so we can see what material that actually is.

**Comment by ChanceSD** [comment] 2019-12-12 17:25
Please try the latest version when you can, enable debug in the config and let me know what gets printed in the console when you type /gate setfrom

**Comment by ChanceSD** [comment] 2019-12-21 20:52
@fathomscript

**Comment by Akashiic** [comment] 2020-02-16 16:25
Sorry for the delay to answer, because I was traveling, but I debugged the command and showed it

---- Minecraft Profiler Results ----
// Hello world

Time span: 20156 ms
Tick span: 245 ticks
// This is approximately 12,16 ticks per second. It should be 20 ticks per second

--- BEGIN PROFILE DUMP ---

[00] levels - 97,59%/97,59%
[01] |   world - 96,19%/93,94%
[02] |   |   tick - 99,38%/93,36%
[03] |   |   |   entities - 70,33%/65,66%
[04] |   |   |   |   regular - 97,67%/64,13%
[05] |   |   |   |   |   tick - 98,19%/62,96%
[06] |   |   |   |   |   |   ai - 49,93%/31,44%
[07] |   |   |   |   |   |   |   newAi - 93,17%/29,29%
[08] |   |   |   |   |   |   |   |   controls - 30,05%/8,80%
[09] |   |   |   |   |   |   |   |   |   move - 25,54%/2,25%
[09] |   |   |   |   |   |   |   |   |   look - 25,37%/2,23%
[09] |   |   |   |   |   |   |   |   |   unspecified - 25,32%/2,23%
[09] |   |   |   |   |   |   |   |   |   jump - 23,76%/2,09%
[08] |   |   |   |   |   |   |   |   goalSelector - 17,33%/5,08%
[09] |   |   |   |   |   |   |   |   |   goalSetup - 50,09%/2,54%
[09] |   |   |   |   |   |   |   |   |   unspecified - 43,36%/2,20%
[09] |   |   |   |   |   |   |   |   |   goalTick - 6,55%/0,33%
[08] |   |   |   |   |   |   |   |   targetSelector - 15,14%/4,44%
[09] |   |   |   |   |   |   |   |   |   goalSetup - 51,02%/2,26%
[09] |   |   |   |   |   |   |   |   |   unspecified - 48,98%/2,17%
[08] |   |   |   |   |   |   |   |   checkDespawn - 7,80%/2,28%
[08] |   |   |   |   |   |   |   |   unspecified - 7,80%/2,28%
[08] |   |   |   |   |   |   |   |   sensing - 7,65%/2,24%
[08] |   |   |   |   |   |   |   |   mob tick - 7,13%/2,09%
[08] |   |   |   |   |   |   |   |   navigation - 7,11%/2,08%
[07] |   |   |   |   |   |   |   unspecified - 6,83%/2,15%
[06] |   |   |   |   |   |   travel - 17,89%/11,26%
[07] |   |   |   |   |   |   |   rest - 47,67%/5,37%
[08] |   |   |   |   |   |   |   |   chunkCheck - 50,98%/2,74%
[08] |   |   |   |   |   |   |   |   unspecified - 49,02%/2,63%
[07] |   |   |   |   |   |   |   move - 30,78%/3,47%
[07] |   |   |   |   |   |   |   unspecified - 21,55%/2,43%
[06] |   |   |   |   |   |   unspecified - 4,81%/3,03%
[06] |   |   |   |   |   |   entityBaseTick - 3,75%/2,36%
[06] |   |   |   |   |   |   livingEntityBaseTick - 3,24%/2,04%
[06] |   |   |   |   |   |   push - 3,10%/1,95%
[06] |   |   |   |   |   |   jump - 3,09%/1,95%
[06] |   |   |   |   |   |   looting - 2,90%/1,83%
[06] |   |   |   |   |   |   mobBaseTick - 2,65%/1,67%
[06] |   |   |   |   |   |   headTurn - 2,47%/1,56%
[06] |   |   |   |   |   |   rangeChecks - 2,29%/1,44%
[06] |   |   |   |   |   |   portal - 2,08%/1,31%
[06] |   |   |   |   |   |   chunkCheck - 1,76%/1,11%
[06] |   |   |   |   |   |   rest - 0,01%/0,01%
[07] |   |   |   |   |   |   |   unspecified - 50,95%/0,00%
[07] |   |   |   |   |   |   |   chunkCheck - 49,05%/0,00%
[06] |   |   |   |   |   |   move - 0,01%/0,01%
[05] |   |   |   |   |   remove - 1,49%/0,96%
[05] |   |   |   |   |   unspecified - 0,32%/0,21%
[04] |   |   |   |   blockEntities - 2,01%/1,32%
[05] |   |   |   |   |   minecraft:chest - 41,59%/0,55%
[05] |   |   |   |   |   minecraft:mob_spawner - 41,36%/0,54%
[05] |   |   |   |   |   unspecified - 10,04%/0,13%
[05] |   |   |   |   |   minecraft:beacon - 6,16%/0,08%
[05] |   |   |   |   |   betterrecords:recordetcher - 0,85%/0,01%
[04] |   |   |   |   players - 0,15%/0,10%
[05] |   |   |   |   |   tick - 71,82%/0,07%
[06] |   |   |   |   |   |   unspecified - 46,21%/0,03%
[06] |   |   |   |   |   |   portal - 34,80%/0,02%
[06] |   |   |   |   |   |   chunkCheck - 18,99%/0,01%
[05] |   |   |   |   |   unspecified - 16,68%/0,02%
[05] |   |   |   |   |   remove - 11,50%/0,01%
[04] |   |   |   |   remove - 0,11%/0,07%
[04] |   |   |   |   global - 0,03%/0,02%
[04] |   |   |   |   unspecified - 0,02%/0,01%
[04] |   |   |   |   pendingBlockEntities - 0,02%/0,01%
[03] |   |   |   tickBlocks - 29,29%/27,34%
[04] |   |   |   |   pollingChunks - 99,90%/27,31%
[05] |   |   |   |   |   tickBlocks - 55,79%/15,24%
[06] |   |   |   |   |   |   randomTick - 81,37%/12,40%
[06] |   |   |   |   |   |   unspecified - 18,63%/2,84%
[05] |   |   |   |   |   tickChunk - 8,58%/2,34%
[05] |   |   |   |   |   iceandsnow - 8,43%/2,30%
[05] |   |   |   |   |   getChunk - 8,38%/2,29%
[05] |   |   |   |   |   thunder - 8,08%/2,21%
[05] |   |   |   |   |   checkNextLight - 7,99%/2,18%
[05] |   |   |   |   |   unspecified - 1,73%/0,47%
[05] |   |   |   |   |   regularChunkLoading - 0,94%/0,26%
[05] |   |   |   |   |   forcedChunkLoading - 0,09%/0,02%
[04] |   |   |   |   playerCheckLight - 0,05%/0,01%
[04] |   |   |   |   unspecified - 0,05%/0,01%
[03] |   |   |   unspecified - 0,22%/0,21%
[03] |   |   |   tickPending - 0,06%/0,05%
[04] |   |   |   |   ticking - 48,87%/0,03%
[04] |   |   |   |   cleaning - 27,47%/0,01%
[04] |   |   |   |   unspecified - 23,65%/0,01%
[03] |   |   |   mobSpawner - 0,05%/0,05%
[03] |   |   |   chunkMap - 0,02%/0,01%
[03] |   |   |   chunkSource - 0,02%/0,01%
[03] |   |   |   portalForcer - 0,01%/0,01%
[03] |   |   |   village - 0,01%/0,01%
[02] |   |   tracker - 0,60%/0,57%
[02] |   |   unspecified - 0,02%/0,02%
[01] |   DIM7 - 0,57%/0,56%
[02] |   |   tick - 80,57%/0,45%
[03] |   |   |   unspecified - 44,02%/0,20%
[03] |   |   |   tickBlocks - 17,84%/0,08%
[04] |   |   |   |   pollingChunks - 49,42%/0,04%
[05] |   |   |   |   |   forcedChunkLoading - 42,59%/0,02%
[05] |   |   |   |   |   regularChunkLoading - 29,60%/0,01%
[05] |   |   |   |   |   unspecified - 27,81%/0,01%
[04] |   |   |   |   playerCheckLight - 36,51%/0,03%
[04] |   |   |   |   unspecified - 14,07%/0,01%
[03] |   |   |   chunkMap - 8,11%/0,04%
[03] |   |   |   entities - 7,06%/0,03%
[04] |   |   |   |   remove - 36,78%/0,01%
[04] |   |   |   |   unspecified - 33,88%/0,01%
[04] |   |   |   |   blockEntities - 29,34%/0,01%
[03] |   |   |   tickPending - 6,92%/0,03%
[04] |   |   |   |   unspecified - 36,42%/0,01%
[04] |   |   |   |   cleaning - 32,33%/0,01%
[04] |   |   |   |   ticking - 31,25%/0,01%
[03] |   |   |   chunkSource - 6,58%/0,03%
[03] |   |   |   mobSpawner - 5,33%/0,02%
[03] |   |   |   village - 2,23%/0,01%
[03] |   |   |   portalForcer - 1,92%/0,01%
[02] |   |   tracker - 17,80%/0,10%
[02] |   |   unspecified - 1,63%/0,01%
[01] |   DIM51 - 0,51%/0,50%
[02] |   |   tick - 96,60%/0,48%
[03] |   |   |   tickPending - 63,54%/0,31%
[04] |   |   |   |   cleaning - 92,12%/0,28%
[04] |   |   |   |   ticking - 4,25%/0,01%
[04] |   |   |   |   unspecified - 3,64%/0,01%
[03] |   |   |   tickBlocks - 12,72%/0,06%
[04] |   |   |   |   pollingChunks - 63,52%/0,04%
[05] |   |   |   |   |   forcedChunkLoading - 38,84%/0,02%
[05] |   |   |   |   |   regularChunkLoading - 31,36%/0,01%
[05] |   |   |   |   |   unspecified - 29,80%/0,01%
[04] |   |   |   |   unspecified - 18,80%/0,01%
[04] |   |   |   |   playerCheckLight - 17,68%/0,01%
[03] |   |   |   entities - 7,12%/0,03%
[04] |   |   |   |   remove - 42,31%/0,01%
[04] |   |   |   |   unspecified - 29,92%/0,01%
[04] |   |   |   |   blockEntities - 27,77%/0,01%
[03] |   |   |   unspecified - 6,42%/0,03%
[03] |   |   |   mobSpawner - 2,38%/0,01%
[03] |   |   |   chunkSource - 2,09%/0,01%
[03] |   |   |   chunkMap - 2,00%/0,01%
[03] |   |   |   village - 1,99%/0,01%
[03] |   |   |   portalForcer - 1,75%/0,01%
[02] |   |   tracker - 1,73%/0,01%
[02] |   |   unspecified - 1,67%/0,01%
[01] |   DIM-1 - 0,39%/0,38%
[02] |   |   tick - 91,54%/0,35%
[03] |   |   |   unspecified - 30,23%/0,11%
[03] |   |   |   tickBlocks - 22,65%/0,08%
[04] |   |   |   |   pollingChunks - 66,91%/0,05%
[05] |   |   |   |   |   forcedChunkLoading - 46,87%/0,02%
[05] |   |   |   |   |   unspecified - 28,21%/0,01%
[05] |   |   |   |   |   regularChunkLoading - 24,93%/0,01%
[04] |   |   |   |   playerCheckLight - 17,89%/0,01%
[04] |   |   |   |   unspecified - 15,20%/0,01%
[03] |   |   |   tickPending - 15,31%/0,05%
[04] |   |   |   |   ticking - 44,57%/0,02%
[04] |   |   |   |   cleaning - 29,49%/0,02%
[04] |   |   |   |   unspecified - 25,94%/0,01%
[03] |   |   |   entities - 9,56%/0,03%
[04] |   |   |   |   remove - 39,32%/0,01%
[04] |   |   |   |   unspecified - 31,91%/0,01%
[04] |   |   |   |   blockEntities - 28,77%/0,01%
[03] |   |   |   mobSpawner - 6,49%/0,02%
[03] |   |   |   chunkSource - 6,12%/0,02%
[03] |   |   |   chunkMap - 4,06%/0,01%
[03] |   |   |   village - 2,96%/0,01%
[03] |   |   |   portalForcer - 2,62%/0,01%
[02] |   |   tracker - 6,06%/0,02%
[02] |   |   unspecified - 2,40%/0,01%
[01] |   DIM52 - 0,30%/0,29%
[02] |   |   tick - 87,94%/0,26%
[03] |   |   |   unspecified - 27,97%/0,07%
[03] |   |   |   tickBlocks - 23,46%/0,06%
[04] |   |   |   |   pollingChunks - 63,66%/0,04%
[05] |   |   |   |   |   forcedChunkLoading - 39,37%/0,02%
[05] |   |   |   |   |   regularChunkLoading - 30,60%/0,01%
[05] |   |   |   |   |   unspecified - 30,04%/0,01%
[04] |   |   |   |   playerCheckLight - 19,42%/0,01%
[04] |   |   |   |   unspecified - 16,92%/0,01%
[03] |   |   |   entities - 13,56%/0,03%
[04] |   |   |   |   remove - 41,31%/0,01%
[04] |   |   |   |   blockEntities - 29,35%/0,01%
[04] |   |   |   |   unspecified - 29,34%/0,01%
[03] |   |   |   tickPending - 11,82%/0,03%
[04] |   |   |   |   unspecified - 37,31%/0,01%
[04] |   |   |   |   cleaning - 32,13%/0,01%
[04] |   |   |   |   ticking - 30,56%/0,01%
[03] |   |   |   chunkSource - 5,94%/0,02%
[03] |   |   |   mobSpawner - 5,39%/0,01%
[03] |   |   |   chunkMap - 4,85%/0,01%
[03] |   |   |   village - 3,63%/0,01%
[03] |   |   |   portalForcer - 3,38%/0,01%
[02] |   |   tracker - 9,31%/0,03%
[02] |   |   unspecified - 2,75%/0,01%
[01] |   DIM17 - 0,30%/0,29%
[02] |   |   tick - 94,17%/0,28%
[03] |   |   |   tickBlocks - 21,39%/0,06%
[04] |   |   |   |   pollingChunks - 63,28%/0,04%
[05] |   |   |   |   |   forcedChunkLoading - 36,69%/0,01%
[05] |   |   |   |   |   regularChunkLoading - 31,84%/0,01%
[05] |   |   |   |   |   unspecified - 31,47%/0,01%
[04] |   |   |   |   unspecified - 18,47%/0,01%
[04] |   |   |   |   playerCheckLight - 18,25%/0,01%
[03] |   |   |   entities - 17,55%/0,05%
[04] |   |   |   |   unspecified - 57,57%/0,03%
[04] |   |   |   |   remove - 23,14%/0,01%
[04] |   |   |   |   blockEntities - 19,30%/0,01%
[03] |   |   |   unspecified - 15,26%/0,04%
[03] |   |   |   tickPending - 11,14%/0,03%
[04] |   |   |   |   unspecified - 37,73%/0,01%
[04] |   |   |   |   cleaning - 32,43%/0,01%
[04] |   |   |   |   ticking - 29,84%/0,01%
[03] |   |   |   forcedChunkLoading - 10,53%/0,03%
[03] |   |   |   regularChunkLoading - 6,02%/0,02%
[03] |   |   |   chunkSource - 4,08%/0,01%
[03] |   |   |   mobSpawner - 3,81%/0,01%
[03] |   |   |   village - 3,58%/0,01%
[03] |   |   |   chunkMap - 3,58%/0,01%
[03] |   |   |   portalForcer - 3,08%/0,01%
[02] |   |   unspecified - 3,01%/0,01%
[02] |   |   tracker - 2,82%/0,01%
[01] |   recursos - 0,29%/0,28%
[02] |   |   tick - 82,79%/0,23%
[03] |   |   |   tickBlocks - 26,42%/0,06%
[04] |   |   |   |   pollingChunks - 63,90%/0,04%
[05] |   |   |   |   |   forcedChunkLoading - 40,22%/0,02%
[05] |   |   |   |   |   unspecified - 30,94%/0,01%
[05] |   |   |   |   |   regularChunkLoading - 28,84%/0,01%
[04] |   |   |   |   playerCheckLight - 18,28%/0,01%
[04] |   |   |   |   unspecified - 17,83%/0,01%
[03] |   |   |   unspecified - 18,62%/0,04%
[03] |   |   |   entities - 13,92%/0,03%
[04] |   |   |   |   remove - 36,03%/0,01%
[04] |   |   |   |   unspecified - 34,18%/0,01%
[04] |   |   |   |   blockEntities - 29,79%/0,01%
[03] |   |   |   tickPending - 13,06%/0,03%
[04] |   |   |   |   unspecified - 34,96%/0,01%
[04] |   |   |   |   cleaning - 33,49%/0,01%
[04] |   |   |   |   ticking - 31,55%/0,01%
[03] |   |   |   mobSpawner - 7,61%/0,02%
[03] |   |   |   village - 6,84%/0,02%
[03] |   |   |   chunkSource - 5,70%/0,01%
[03] |   |   |   chunkMap - 4,13%/0,01%
[03] |   |   |   portalForcer - 3,70%/0,01%
[02] |   |   tracker - 14,03%/0,04%
[02] |   |   unspecified - 3,18%/0,01%
[01] |   DIM1 - 0,26%/0,25%
[02] |   |   tick - 92,98%/0,23%
[03] |   |   |   tickBlocks - 28,37%/0,07%
[04] |   |   |   |   pollingChunks - 64,48%/0,04%
[05] |   |   |   |   |   forcedChunkLoading - 40,03%/0,02%
[05] |   |   |   |   |   regularChunkLoading - 30,00%/0,01%
[05] |   |   |   |   |   unspecified - 29,98%/0,01%
[04] |   |   |   |   playerCheckLight - 18,10%/0,01%
[04] |   |   |   |   unspecified - 17,42%/0,01%
[03] |   |   |   unspecified - 18,89%/0,04%
[03] |   |   |   tickPending - 13,75%/0,03%
[04] |   |   |   |   cleaning - 36,05%/0,01%
[04] |   |   |   |   unspecified - 34,97%/0,01%
[04] |   |   |   |   ticking - 28,98%/0,01%
[03] |   |   |   entities - 13,74%/0,03%
[04] |   |   |   |   remove - 37,02%/0,01%
[04] |   |   |   |   unspecified - 33,93%/0,01%
[04] |   |   |   |   blockEntities - 29,05%/0,01%
[03] |   |   |   chunkSource - 6,62%/0,02%
[03] |   |   |   mobSpawner - 5,86%/0,01%
[03] |   |   |   chunkMap - 4,58%/0,01%
[03] |   |   |   village - 4,30%/0,01%
[03] |   |   |   portalForcer - 3,90%/0,01%
[02] |   |   tracker - 3,53%/0,01%
[02] |   |   unspecified - 3,48%/0,01%
[01] |   DIM-11325 - 0,23%/0,22%
[02] |   |   tick - 92,58%/0,21%
[03] |   |   |   tickBlocks - 29,23%/0,06%
[04] |   |   |   |   pollingChunks - 62,27%/0,04%
[05] |   |   |   |   |   forcedChunkLoading - 38,28%/0,01%
[05] |   |   |   |   |   unspecified - 31,38%/0,01%
[05] |   |   |   |   |   regularChunkLoading - 30,34%/0,01%
[04] |   |   |   |   unspecified - 18,93%/0,01%
[04] |   |   |   |   playerCheckLight - 18,80%/0,01%
[03] |   |   |   unspecified - 16,23%/0,03%
[03] |   |   |   tickPending - 14,77%/0,03%
[04] |   |   |   |   unspecified - 34,94%/0,01%
[04] |   |   |   |   cleaning - 34,41%/0,01%
[04] |   |   |   |   ticking - 30,65%/0,01%
[03] |   |   |   entities - 14,76%/0,03%
[04] |   |   |   |   remove - 35,59%/0,01%
[04] |   |   |   |   unspecified - 33,38%/0,01%
[04] |   |   |   |   blockEntities - 31,04%/0,01%
[03] |   |   |   mobSpawner - 5,96%/0,01%
[03] |   |   |   chunkSource - 5,47%/0,01%
[03] |   |   |   chunkMap - 4,71%/0,01%
[03] |   |   |   village - 4,59%/0,01%
[03] |   |   |   portalForcer - 4,28%/0,01%
[02] |   |   unspecified - 3,95%/0,01%
[02] |   |   tracker - 3,47%/0,01%
[01] |   DIM2 - 0,23%/0,22%
[02] |   |   tick - 92,88%/0,21%
[03] |   |   |   tickBlocks - 29,02%/0,06%
[04] |   |   |   |   pollingChunks - 63,67%/0,04%
[05] |   |   |   |   |   forcedChunkLoading - 38,66%/0,01%
[05] |   |   |   |   |   regularChunkLoading - 32,03%/0,01%
[05] |   |   |   |   |   unspecified - 29,31%/0,01%
[04] |   |   |   |   playerCheckLight - 18,20%/0,01%
[04] |   |   |   |   unspecified - 18,12%/0,01%
[03] |   |   |   unspecified - 15,57%/0,03%
[03] |   |   |   entities - 14,87%/0,03%
[04] |   |   |   |   remove - 35,30%/0,01%
[04] |   |   |   |   unspecified - 34,67%/0,01%
[04] |   |   |   |   blockEntities - 30,02%/0,01%
[03] |   |   |   tickPending - 14,80%/0,03%
[04] |   |   |   |   unspecified - 37,33%/0,01%
[04] |   |   |   |   cleaning - 31,82%/0,01%
[04] |   |   |   |   ticking - 30,85%/0,01%
[03] |   |   |   mobSpawner - 5,65%/0,01%
[03] |   |   |   chunkSource - 5,62%/0,01%
[03] |   |   |   village - 5,10%/0,01%
[03] |   |   |   chunkMap - 5,00%/0,01%
[03] |   |   |   portalForcer - 4,36%/0,01%
[02] |   |   unspecified - 3,76%/0,01%
[02] |   |   tracker - 3,36%/0,01%
[01] |   DIM-9999 - 0,23%/0,22%
[02] |   |   tick - 92,86%/0,21%
[03] |   |   |   tickBlocks - 28,52%/0,06%
[04] |   |   |   |   pollingChunks - 63,19%/0,04%
[05] |   |   |   |   |   forcedChunkLoading - 38,38%/0,01%
[05] |   |   |   |   |   regularChunkLoading - 31,85%/0,01%
[05] |   |   |   |   |   unspecified - 29,77%/0,01%
[04] |   |   |   |   playerCheckLight - 18,50%/0,01%
[04] |   |   |   |   unspecified - 18,30%/0,01%
[03] |   |   |   entities - 15,52%/0,03%
[04] |   |   |   |   remove - 35,64%/0,01%
[04] |   |   |   |   unspecified - 33,18%/0,01%
[04] |   |   |   |   blockEntities - 31,17%/0,01%
[03] |   |   |   unspecified - 15,49%/0,03%
[03] |   |   |   tickPending - 15,01%/0,03%
[04] |   |   |   |   unspecified - 39,28%/0,01%
[04] |   |   |   |   cleaning - 30,55%/0,01%
[04] |   |   |   |   ticking - 30,16%/0,01%
[03] |   |   |   chunkSource - 5,86%/0,01%
[03] |   |   |   village - 5,33%/0,01%
[03] |   |   |   mobSpawner - 5,29%/0,01%
[03] |   |   |   chunkMap - 4,86%/0,01%
[03] |   |   |   portalForcer - 4,11%/0,01%
[02] |   |   unspecified - 3,78%/0,01%
[02] |   |   tracker - 3,36%/0,01%
[01] |   DIM53 - 0,23%/0,22%
[02] |   |   tick - 92,87%/0,20%
[03] |   |   |   tickBlocks - 30,90%/0,06%
[04] |   |   |   |   pollingChunks - 65,08%/0,04%
[05] |   |   |   |   |   forcedChunkLoading - 42,97%/0,02%
[05] |   |   |   |   |   regularChunkLoading - 28,71%/0,01%
[05] |   |   |   |   |   unspecified - 28,31%/0,01%
[04] |   |   |   |   playerCheckLight - 18,19%/0,01%
[04] |   |   |   |   unspecified - 16,73%/0,01%
[03] |   |   |   tickPending - 15,51%/0,03%
[04] |   |   |   |   unspecified - 35,86%/0,01%
[04] |   |   |   |   ticking - 32,99%/0,01%
[04] |   |   |   |   cleaning - 31,15%/0,01%
[03] |   |   |   entities - 15,06%/0,03%
[04] |   |   |   |   remove - 34,74%/0,01%
[04] |   |   |   |   blockEntities - 33,11%/0,01%
[04] |   |   |   |   unspecified - 32,15%/0,01%
[03] |   |   |   unspecified - 14,10%/0,03%
[03] |   |   |   mobSpawner - 6,02%/0,01%
[03] |   |   |   chunkSource - 5,00%/0,01%
[03] |   |   |   chunkMap - 4,85%/0,01%
[03] |   |   |   village - 4,45%/0,01%
[03] |   |   |   portalForcer - 4,11%/0,01%
[02] |   |   unspecified - 3,59%/0,01%
[02] |   |   tracker - 3,54%/0,01%
[01] |   DIM50 - 0,23%/0,22%
[02] |   |   tick - 92,71%/0,20%
[03] |   |   |   tickBlocks - 30,06%/0,06%
[04] |   |   |   |   pollingChunks - 65,15%/0,04%
[05] |   |   |   |   |   forcedChunkLoading - 36,88%/0,01%
[05] |   |   |   |   |   unspecified - 34,16%/0,01%
[05] |   |   |   |   |   regularChunkLoading - 28,96%/0,01%
[04] |   |   |   |   playerCheckLight - 17,66%/0,01%
[04] |   |   |   |   unspecified - 17,20%/0,01%
[03] |   |   |   unspecified - 15,42%/0,03%
[03] |   |   |   tickPending - 15,14%/0,03%
[04] |   |   |   |   unspecified - 35,55%/0,01%
[04] |   |   |   |   cleaning - 33,86%/0,01%
[04] |   |   |   |   ticking - 30,59%/0,01%
[03] |   |   |   entities - 14,62%/0,03%
[04] |   |   |   |   remove - 35,73%/0,01%
[04] |   |   |   |   unspecified - 33,33%/0,01%
[04] |   |   |   |   blockEntities - 30,93%/0,01%
[03] |   |   |   mobSpawner - 5,72%/0,01%
[03] |   |   |   chunkSource - 5,38%/0,01%
[03] |   |   |   chunkMap - 4,87%/0,01%
[03] |   |   |   village - 4,74%/0,01%
[03] |   |   |   portalForcer - 4,04%/0,01%
[02] |   |   unspecified - 3,76%/0,01%
[02] |   |   tracker - 3,53%/0,01%
[01] |   unspecified - 0,06%/0,05%
[00] connection - 0,94%/0,94%
[01] |   unspecified - 55,11%/0,52%
[01] |   travel - 16,56%/0,16%
[02] |   |   rest - 40,55%/0,06%
[03] |   |   |   unspecified - 53,21%/0,03%
[03] |   |   |   chunkCheck - 46,79%/0,03%
[02] |   |   move - 33,95%/0,05%
[02] |   |   unspecified - 25,49%/0,04%
[01] |   entityBaseTick - 6,91%/0,06%
[01] |   ai - 5,19%/0,05%
[02] |   |   newAi - 52,63%/0,03%
[02] |   |   unspecified - 47,37%/0,02%
[01] |   livingEntityBaseTick - 3,08%/0,03%
[01] |   push - 2,96%/0,03%
[01] |   chunkCheck - 2,82%/0,03%
[01] |   headTurn - 2,21%/0,02%
[01] |   jump - 1,96%/0,02%
[01] |   rangeChecks - 1,70%/0,02%
[01] |   keepAlive - 1,49%/0,01%
[00] jobs - 0,35%/0,35%
[01] |   unspecified - 96,53%/0,34%
[01] |   chunkCheck - 1,40%/0,00%
[01] |   move - 1,04%/0,00%
[01] |   rest - 1,03%/0,00%
[02] |   |   chunkCheck - 50,84%/0,00%
[02] |   |   unspecified - 49,16%/0,00%
[00] rest - 0,29%/0,29%
[01] |   unspecified - 50,92%/0,15%
[01] |   chunkCheck - 49,08%/0,14%
[00] move - 0,20%/0,20%
[00] entityBaseTick - 0,17%/0,17%
[00] livingEntityBaseTick - 0,15%/0,15%
[00] portal - 0,10%/0,10%
[00] chunkCheck - 0,08%/0,08%
[00] ServerTickEvent_END - 0,04%/0,04%
[00] ServerTickEvent_START - 0,03%/0,03%
[00] players - 0,02%/0,02%
[00] dim_unloading - 0,01%/0,01%
[00] commandFunctions - 0,01%/0,01%
[00] tickables - 0,01%/0,01%
[00] snooper - 0,01%/0,01%
[00] tallying - 0,01%/0,01%
--- END PROFILE DUMP ---

**Comment by Goubkev** [comment] 2020-03-02 12:22
Hi, I'm French, sorry for my English.
I have same problem with a portal. I use a last version of Ancient Gate in 1.15.2. Use a vanilla block and have this message "There is not enough room for a gate to open here".
The portal has delete and I'snt possible place block in the portal delete.
Have you a solution for this ?
Thanks for your response.

**Comment by ChanceSD** [comment] 2021-06-06 19:30
I'm going to close this since I can't reproduce the issue or it probably happens only in modded servers. However, if someone manages to find a solution or has more info I don't mind reopening this or attempting a fix.

**Closed as completed by ChanceSD** 2021-06-06 19:30 UTC
Labels: bug
